services:
  app:
    build: .
    container_name: book-catalog-api
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - book-net

  redis:
    image: redis:8.2
    container_name: redis
    command: ["redis-server", "--save", ""]
    ports:
      - "6379:6379"
    networks:
      - book-net

networks:
  book-net: